### ISSUE TITLE
Add Satra to collaborators

### ISSUE THREAD

**Issue by yarikoptic** [con/centerforopenneuroscience.org#24]
I have already added a stub for you @satra to appear on http://centerforopenneuroscience.org/whoweare#collaborators_ .  It is here: https://github.com/con/centerforopenneuroscience.org/blob/master/content/pages/whoweare.html#L193  but not yet published -- want to get your blessing and/or what to add/remove.

Cheers,

**Comment by satra** [comment]
blessed. have to be a fellow plumber.
