### ISSUE TITLE
Is the Center for Open Neuroscience Open?

### ISSUE THREAD

**Issue by r03ert0** [con/centerforopenneuroscience.org#25]
hello! I was visiting CON's virtual booth at OHBM, and your webpage, and didn't find information about this. Is CON itself open? What is the procedure to become a participating project? Is CON designed for open, with an open governance? Or the projects hosted are open while CON itself is not? It's probably a type of information that should be provided, you know, openly :p

**Comment by r03ert0** [comment]
that said... the name is Center for open neuroscience and not Open center for neuroscience... although it could be the open center for open neuroscience

**Comment by yarikoptic** [comment]
ATM CON is pretty much my "lab page". I list/include affiliated faculty from the department and their projects. I list projects I work on and collaborate with. I don't mind transforming it into something bigger, although indeed Open Center for Open Neuroscience would then be more appropriate. I would not be able to pull that of myself though...

**Comment by r03ert0** [comment]
aaaAAaahh! I get it now :D
OCON sounds like a lovely idea for the future (in Chile there's a city called CON-CON, that could be the headquarters)

**Comment by yarikoptic** [comment]
> (in Chile there's a city called CON-CON, that could be the headquarters)

;-) would love that ;) never was to Chile yet
