### ISSUE TITLE
Nibotmi link broken

### ISSUE THREAD

**Issue by asmacdo** [con/centerforopenneuroscience.org#59]
On https://centerforopenneuroscience.org/projects, the link http://nipy.bic.berkeley.edu/waterfall is broken.

In fact, all of http://nipy.bic.berkeley.edu seems to no longer exist and the [Nibotmi gh](https://github.com/nipy/nibotmi) doesn't appear to be maintained (it still links to  http://nipy.bic.berkeley.edu) 

@yarikoptic maybe we should remove this project?

**Comment by yarikoptic** [comment]
yes, we can remove -- no more of that thing
